general:
  description: !ENV example configuration with env ${PATH} # noqa
  name: example
git: null
input_data:
  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: experiments/e004/SV_Italy_PV_timeseries_batch.netcdf
        pv_metadata_filename: experiments/e004/SV_Italy_systems_metadata.csv
    get_center: false
    pv_image_size_meters_height: 100
    pv_image_size_meters_width: 100
    n_pv_systems_per_example: 1
    history_minutes: 240
    forecast_minutes: 240
    start_datetime: 2022-01-01 00:00
    end_datetime: 2022-10-01 00:00
    time_resolution_minutes: 15
  nwp:
    nwp_zarr_path: experiments/e004/gfs.zarr
    history_minutes: 0
    forecast_minutes: 240
    time_resolution_minutes: 60
    start_datetime: 2022-01-01 00:00
    end_datetime: 2022-10-01 00:00
    nwp_image_size_pixels_height: 2
    nwp_image_size_pixels_width: 2

output_data:
  filepath: not used by experiments!
process:
  batch_size: 32
  local_temp_path: ~/temp/
  seed: 1234
  upload_every_n_batches: 16
  n_train_batches: 90
  n_validation_batches: 10
  n_test_batches: 10
  train_test_validation_split: [3, 0, 1]
